project_id = "yyuoyitapltnuqhkjyfd"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.shopify-order-webhook]
    verify_jwt = false
  [functions.admin-dashboard-data]
    verify_jwt = false
